[package]
name = "detect-non-ascii"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
